### PR TITLE
Fix #308 Failed crawls should not be logged as ERROR, but WARN or below

### LINKED ISSUE #308: Failed crawls should not be logged as ERROR, but WARN or below

### PR DESCRIPTION
**Pull request by ComLock**

### CODE REVIEW

File: src/main/resources/lib/explorer/task/constructProgress.ts [hunk 1]
```diff
@@ -102,6 +102,10 @@ function setMessage(message :string) {
 	return this; // chainable
 }
 
+function warn() {
+	log.warning(`[${this._current}/${this._total}] ${this.getInfoString()}`);
+	return this; // chainable
+}
```
Comment (alansemenov) [inline src/main/resources/lib/explorer/task/constructProgress.ts:108]: This one doesn't seem to be used?

**Review by alansemenov — APPROVED** [review]

File: src/main/resources/lib/explorer/task/constructProgress.ts (hunk 1 above)
Comment (ComLock) [reply src/main/resources/lib/explorer/task/constructProgress.ts:109]: Ah, now it's part of the "class" at least
